store: sqlite
embed: ollama
llm: ollama
namespaces:
  default:
    default: true
    description: Default namespace
    cognitive_tools:
      - observe
      - query
      - recall
      - neighbors
      - predict
    collections_prefix: ''
embed_options:
  ollama_model: nomic-embed-text
  ollama_url: http://localhost:11434
llm_options:
  ollama_model: qwen2.5:14b
  ollama_url: http://localhost:11434